#Database
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: Abdulmedi0906
POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: spcloud

#Server
SERVER_PORT: 8080
ACTIVE_PROFILE: prod

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: nassurabdulhamid49@gmail.com
EMAIL_PASSWORD: rork thoj yvwb dpij
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}